name: API Tests CI

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Download and Unpack Application
        env:
          DOWNLOAD_URL: ${{ secrets.APP_DOWNLOAD_URL }}
          ARCHIVE_PWD: ${{ secrets.APP_ARCHIVE_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y p7zip-full
          wget "$DOWNLOAD_URL" -O aqa.7z
          7z x aqa.7z -p"$ARCHIVE_PWD" -y -aos

      - name: Start Target Application (Docker)
        run: |
          # Теперь .jar файл лежит в корне, так как мы его только что распаковали
          docker run -d --network host -v ${{ github.workspace }}:/app -w /app eclipse-temurin:17-jre java -jar -Dsecret=qazWSXedc -Dmock=http://localhost:8888/ internal-0.0.1-SNAPSHOT.jar
          echo "Waiting for Spring Boot to start..."
          sleep 15 

      - name: Run Maven Tests
        run: mvn clean test
        continue-on-error: true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history